### ISSUE TITLE
Null Exception when Enum value is null

### ISSUE THREAD

**Issue by filipe-silva** [StevenThuriot/dotnet-openapi-generator#5]
Hi,

when I tried to generate an api from:
https://api-docs.firefly-iii.org/?urls.primaryName=2.0.10%20(v2)

It gave an exception for "AutoBudgetPeriod", although there are a few more enums, on this code:
`
class: SwaggerSchemaEnum
line 30: name = value.ToString() ?? "";
`

I fixed it by doing this:

`
else
{
    name = value?.ToString() ?? "";
}

if (string.IsNullOrWhiteSpace(name) == false)
{
    if (Char.IsDigit(name[0]))
    {
        name = "_" + name;
    }

    if (!unique.Add(name))
    {
        continue;
    }
}
`

but it doesn't seem right to me..

**Comment by LieselThuriot** [comment]
Do you happen to have the json file you used to generate?
From what I can see, the link you posted only has yaml files available.

I will try to reproduce the issue and see what's going wrong if you can link me the file.

**Comment by LieselThuriot** [comment]
I couldn't find the enum in the V2 you linked, but after looking at the yaml file for v1 I noticed this:

```yml
    AutoBudgetPeriod:
      type: string
      format: string
      example: "monthly"
      nullable: true
      description: "Period for the auto budget"
      enum:
        - daily
        - weekly
        - monthly
        - quarterly
        - "half-year"
        - yearly
        - null
```

Also pulled it through a YAML to JSON converter and got this:

```json
      "AutoBudgetPeriod": {
        "type": "string",
        "format": "string",
        "example": "monthly",
        "nullable": true,
        "description": "Period for the auto budget",
        "enum": [
          "daily",
          "weekly",
          "monthly",
          "quarterly",
          "half-year",
          "yearly",
          null
        ]
      }
```

It seems like it's adding null as one of the values for the nullable enums, which I did not expect nor have for the swagger documents I generated myself.

The fix for that is fairly easy and I will try and push it in the following days.

However, `"half-year"` is a whole other issue as there's no support yet for this. 
The code currently assumes the enum's can be directly ToString'ed for query parameters and System.Text.json has no support yet for `EnumMemberAttribute` when used in a body. 

This would require generating custom serializers when an enum has this and seeing it's only loosely coupled to System.Text.Json, that might be quite an annnoying hurdle to tackle 😢 Most likely I won't have a quick fix for this, but I will look into it.
